---
title: "Class"
author: "Cian Stryker"
date: "2/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(skimr)
library(rstanarm)
library(tidyverse)
```

```{r}
load("nes.rda")

y <- nes %>%
    select(year, partyid7, real_ideo, race_adj, age_discrete, educ1, female, income) %>%
    group_by(year) %>%
    count(real_ideo)

y2 <- aggregate(n ~ year, data = y, FUN = sum)
```

```{r}
x <- nes %>%
    select(year, partyid7, real_ideo, race_adj, age_discrete, educ1, female, income) %>%
    drop_na() %>%
    mutate(gender = as.factor(ifelse(female == 1, "female", "non-female")))
```

```{r}
fit_1 <- stan_glm(partyid7 ~ gender, data = x, refresh = 0)

print(fit_1)
```


```{r}
x2 <- x %>%
  filter(gender == "non-female") %>%
  group_by(partyid7) %>%
  count(partyid7)

x3 <- x2 %>%
  head(5) %>%
  ungroup() %>%
  summarize(total = sum(n))

x4 <- x2 %>%
  tail(2) %>%
  ungroup() %>%
  summarize(total = sum(n))

x5 <- x3 + x4

answer <- x3/x5
```

```{r}
w <- x %>%
  mutate(pred = predict(fit_1, x)) %>%
  select(partyid7, gender, pred)
```

```{r}
 v<- nes %>%
    select(year, partyid7, real_ideo, race_adj, age_discrete, educ1, female, income) %>%
    drop_na() %>%
    mutate(race = as.factor(case_when(race_adj == 1 ~ "White",
                                      race_adj == 1.5 ~ "Other", 
                                    race_adj == 2 ~ "Black")))

fit_2 <- stan_glm(partyid7 ~ race, data = v, refresh = 0)
```

```{r}
print(fit_2)


w2 <- v %>%
  mutate(pred = predict(fit_2, v)) %>%
  select(partyid7, race, pred)
```

Intercept is Basline Black Median. I.e. White median is 4 or baseline + Median 1.9